apiVersion: v1
kind: Secret
metadata:
  name: mi-go-devops-secret
type: Opaque
data:
  # Variables codificadas en base64 (ejemplo)
  # Para codificar: echo -n "mi-password" | base64
  DB_PASSWORD: noahbele130821==  # Password de base de datos (ejemplo)