apiVersion: v1
kind: Service
metadata:
  name: mi-go-devops-service
  labels:
    app: mi-go-devops
spec:
  # Tipo ClusterIP para acceso interno en el cluster
  type: ClusterIP
  ports:
  - port: 80          # Puerto del servicio (externo)
    targetPort: 8080  # Puerto del contenedor (interno)
    protocol: TCP
    name: http
  selector:
    app: mi-go-devops # Selecciona pods con esta etiqueta